#!/usr/bin/env python
# -*- coding: utf-8 -*-

from i3tools.message import i3msg
from six import print_
import sys


if __name__ == '__main__':
    if len(sys.argv) != 2 or sys.argv[1] not in ['prev', 'next']:
        print_('Usage: i3ws <prev|next>', file=sys.stderr)
        sys.exit(1)

    workspaces = i3msg('get_workspaces', None)

    i = 0
    for ws in workspaces:
        if i >= len(workspaces) - 1:
            i = -1

        change_to = (i - 1) if sys.argv[1] == 'prev' else (i + 1)

        if ws['focused']:
            i3msg(None, 'workspace {0}'.format(workspaces[change_to]['name']))

        i += 1
